### ISSUE TITLE
npm start problem :(

### ISSUE THREAD

**Issue by canpekdemir1** [codevet/daipay#2]
this problem
hello
I'm NEW IN GITHUB
I couldn't find where to write my problem
I get such error on npm startup

root@myhost ~]# cd
[root@myhost ~]# cd home
[root@myhost ~]# cd node
[root@myhost ~]# npm start
npm ERR! Error: ENOENT, open '/root/package.json'
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/npm/npm/issues

npm ERR! System Linux 3.10.0-1062.9.1.el7.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /root
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! /root/npm-debug.log
npm ERR! not ok code 0
[root@myhost ~]

How to fix this problem

**Comment by defisapiens** [comment]
See the README for detailed instructions  (the "Installation" section)
